import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import dotenv from "dotenv";
import matter from "gray-matter";
import sharp from "sharp";
import YAML from "yaml";

export const root = path.resolve(".");
dotenv.config({ path: path.join(root, ".env"), quiet: true });
dotenv.config({ path: path.join(root, ".env.local"), override: false, quiet: true });
export const automationRoot = path.join(root, "automation", "social-media");
export const contentRoot = path.resolve(root, process.env.SOCIAL_CONTENT_ROOT || "social-content");
export const publicRoot = path.join(root, "public", "generated-social");
export const states = ["topic_detected", "topic_approved", "awaiting_user_asset", "asset_received", "generation_requested", "creative_generated", "creative_review_required", "creative_approved", "ready_to_publish", "publishing", "published", "failed", "skipped"];

export function now() { return new Date().toISOString(); }
export function json(file, fallback = null) { return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : fallback; }
export function writeJson(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); }
export function appendLog(event) { const file = path.join(root, "logs", "social-automation.jsonl"); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.appendFileSync(file, `${JSON.stringify({ at: now(), ...event })}\n`); }
export function parseArgs(values = process.argv.slice(3)) { const result = { _: [] }; for (let i = 0; i < values.length; i += 1) { const item = values[i]; if (!item.startsWith("--")) result._.push(item); else { const key = item.slice(2); const next = values[i + 1]; result[key] = !next || next.startsWith("--") ? true : next; if (result[key] !== true) i += 1; } } return result; }
export function config() { const read = (name) => YAML.parse(fs.readFileSync(path.join(automationRoot, "config", name), "utf8")); return { ...read("business-profile.yaml"), brand: read("brand-profile.yaml").brand, settings: read("social-settings.yaml") }; }
export function ensureRoots() { ["pending", "awaiting-assets", "drafts", "previews", "approved", "published", "failed", "skipped"].forEach((dir) => fs.mkdirSync(path.join(contentRoot, dir), { recursive: true })); ["images", "videos", "thumbnails"].forEach((dir) => fs.mkdirSync(path.join(publicRoot, dir), { recursive: true })); }
function recordDir(status) { if (status === "awaiting_user_asset") return "awaiting-assets"; if (status === "published") return "published"; if (status === "failed") return "failed"; if (status === "skipped") return "skipped"; return "drafts"; }
function recordPath(record) { return path.join(contentRoot, recordDir(record.workflow_status), `${record.topic_id}.json`); }
export function allRecords() { ensureRoots(); const dirs = ["pending", "awaiting-assets", "drafts", "previews", "approved", "published", "failed", "skipped"]; return dirs.flatMap((dir) => fs.readdirSync(path.join(contentRoot, dir)).filter((f) => f.endsWith(".json")).map((f) => json(path.join(contentRoot, dir, f))).filter(Boolean)); }
export function getRecord(topicId) { const record = allRecords().find((item) => item.topic_id === topicId || item.blog_slug === topicId); if (!record) throw new Error(`No social record found for '${topicId}'. Run social:detect first.`); return record; }
export function saveRecord(record) { ensureRoots(); record.updated_at = now(); const target = recordPath(record); for (const dir of ["pending", "awaiting-assets", "drafts", "previews", "approved", "published", "failed", "skipped"]) { const candidate = path.join(contentRoot, dir, `${record.topic_id}.json`); if (candidate !== target && fs.existsSync(candidate)) fs.unlinkSync(candidate); } writeJson(target, record); return record; }
export function transition(record, status, detail = {}) { if (!states.includes(status)) throw new Error(`Unknown social state '${status}'.`); record.workflow_status = status; record.history ||= []; record.history.push({ state: status, at: now(), ...detail }); return saveRecord(record); }
export function safeRelativeAsset(input) { if (!input || path.isAbsolute(input) || input.includes("..")) throw new Error("Asset path must be a safe relative repository path."); const absolute = path.resolve(root, input); if (!absolute.startsWith(`${root}${path.sep}`) || !fs.existsSync(absolute)) throw new Error("Asset does not exist inside the repository."); return absolute; }
function extensionMime(file) { const ext = path.extname(file).toLowerCase(); return ({ ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp", ".mp4": "video/mp4", ".mov": "video/quicktime" })[ext] || "application/octet-stream"; }
function copyAsset(record, source, containsChildren, consentStatus) { const settings = config().settings.workflow; const mime = extensionMime(source); const allowed = [...settings.allowed_image_types, ...settings.allowed_video_types]; if (!allowed.includes(mime)) throw new Error(`Unsupported asset type '${mime}'.`); const stat = fs.statSync(source); if (stat.size > settings.max_asset_bytes) throw new Error("Asset exceeds configured size limit."); if (containsChildren && consentStatus !== "confirmed") throw new Error("Identifiable children require recorded written consent before use."); const ext = path.extname(source).toLowerCase(); const original = path.join(contentRoot, "awaiting-assets", record.topic_id, `original${ext}`); const working = path.join(contentRoot, "drafts", record.topic_id, `working${ext}`); fs.mkdirSync(path.dirname(original), { recursive: true }); fs.mkdirSync(path.dirname(working), { recursive: true }); fs.copyFileSync(source, original); fs.copyFileSync(source, working); return { original_path: path.relative(contentRoot, original), working_path: path.relative(contentRoot, working), mime, bytes: stat.size, contains_children: containsChildren, consent_status: consentStatus, supplied_at: now() };
}
export async function inspectAsset(record) { if (!record.asset?.working_path) throw new Error("No received asset is available to inspect."); const absolute = path.resolve(contentRoot, record.asset.working_path); if (record.asset.mime.startsWith("image/")) { const metadata = await sharp(absolute).metadata(); record.asset.analysis = { width: metadata.width, height: metadata.height, format: metadata.format, suggestion: metadata.width >= 1080 && metadata.height >= 1080 ? "Use unchanged or crop for platform framing." : "Source is below preferred social resolution; replace or enhance only with approval." }; } else record.asset.analysis = { suggestion: "Preserved unchanged. Video trim/crop requires a separate approved processing step." };
 return saveRecord(record);
}
function readBlogMetadata() { const dir = path.join(root, "seo-automation", "generated-blogs"); if (!fs.existsSync(dir)) return []; return fs.readdirSync(dir).filter((file) => file.endsWith(".json")).map((file) => json(path.join(dir, file))).filter((item) => item?.workflow_status === "approved_for_publish"); }
function blogDetails(topic) { const absolute = path.resolve(root, topic.draft_path); const frontmatter = fs.existsSync(absolute) ? matter(fs.readFileSync(absolute, "utf8")).data : {}; return { title: topic.title || frontmatter.title || topic.slug, url: frontmatter.canonical || `${config().business.website_url.replace(/\/$/, "")}/blog/${topic.slug}/`, primary_keyword: topic.primary_keyword || frontmatter.primary_keyword || "", supporting_keywords: topic.supporting_keywords || frontmatter.supporting_keywords || [], search_intent: topic.search_intent || "informational", audience: topic.target_audience || "prospective students and families" }; }
export function detect() { const records = allRecords(); const approved = readBlogMetadata().sort((a, b) => String(b.approval_date || b.generated_at).localeCompare(String(a.approval_date || a.generated_at))); const active = records.find((record) => !["published", "skipped", "failed"].includes(record.workflow_status)); if (active) return { record: active, created: false, message: "An active social request already exists." }; const topic = approved.find((item) => !records.some((record) => record.topic_id === item.id && ["published", "skipped"].includes(record.workflow_status))); if (!topic) return { record: null, created: false, message: "No eligible final-approved blog topic." }; const details = blogDetails(topic); const record = { version: 1, topic_id: topic.id, blog_id: topic.id, blog_slug: topic.slug, blog: details, source_workflow_status: topic.workflow_status, workflow_status: "topic_detected", created_at: now(), history: [{ state: "topic_detected", at: now() }], platform_results: {}, ai_calls: [] }; saveRecord(record); appendLog({ event: "topic_detected", topic_id: record.topic_id }); return { record, created: true, message: "Eligible final-approved blog topic detected." }; }
export function createBrief(record, { refresh = false } = {}) { if (record.brief && !refresh) return record; const business = config().business; const title = record.blog.title.replace(/[:–—].*$/, ""); const selfDefence = /self.defence/i.test(title); const headline = selfDefence ? "Self-Defence Starts Here" : "Focused Practice Starts Here"; const angle = `A practical next step for ${record.blog.audience}.`;
 record.brief = { topic_id: record.topic_id, blog_slug: record.blog_slug, blog_title: record.blog.title, blog_url: record.blog.url, primary_keyword: record.blog.primary_keyword, supporting_keywords: record.blog.supporting_keywords, search_intent: record.blog.search_intent, audience: record.blog.audience, social_angle: angle, main_message: title, headline, supporting_text: "Build confidence through focused practice.", call_to_action: business.preferred_cta, website_url: business.website_url, instagram_handle: `@${config().social.instagram_username}`, format_recommendation: "image", visual_concept: "Warm ivory training-inspired abstract scene with disciplined green geometry and a restrained orange accent.", facebook_caption: `Practical self-defence starts with focused learning and consistent practice.\n\nExplore the full guide: ${record.blog.url}\n\n${business.preferred_cta}.`, instagram_caption: `Confidence can start with one practical step.\n\nExplore the full guide and take the next step when you are ready.\n\n#Karate #Fitness #SelfDefence #Mumbai` };
 if (record.workflow_status === "topic_detected") transition(record, "topic_approved", { detail: "Social brief created from final-approved blog metadata." }); else saveRecord(record); return record;
}
export function requestAsset(record) { createBrief(record); if (record.workflow_status === "awaiting_user_asset") return record; if (!["topic_approved", "topic_detected"].includes(record.workflow_status)) throw new Error(`Cannot request an asset while record is ${record.workflow_status}.`); return transition(record, "awaiting_user_asset", { question: "Do you have your own image or video for today's post?", choices: ["upload-image", "upload-video", "repository-asset", "generate-image", "skip"] }); }
export async function receiveAsset(record, args) { if (record.workflow_status !== "awaiting_user_asset") throw new Error("Asset responses are accepted only while awaiting_user_asset."); const choice = args.choice; if (!['upload-image', 'upload-video', 'repository-asset', 'generate-image', 'skip'].includes(choice)) throw new Error("--choice must be upload-image, upload-video, repository-asset, generate-image, or skip."); if (choice === "skip") return transition(record, "skipped", { reason: args.reason || "User skipped today's social post." }); if (choice === "generate-image") { record.asset_decision = { choice, at: now() }; return transition(record, "generation_requested", { provider: args.provider || "interactive_manifest" }); }
 if (!args.path) throw new Error("--path is required for uploaded or repository assets."); const containsChildren = String(args['contains-children']) === "true"; const consent = args.consent || "not_confirmed"; record.asset_decision = { choice, at: now() }; record.asset = copyAsset(record, safeRelativeAsset(args.path), containsChildren, consent); transition(record, "asset_received", { asset: record.asset.original_path }); await inspectAsset(record); return record;
}
function fillTemplate(name, values) { let text = fs.readFileSync(path.join(automationRoot, "prompts", name), "utf8"); for (const [key, value] of Object.entries(values)) text = text.replaceAll(`{{${key}}}`, String(value)); return text; }
export async function generateCreative(record, args) { if (!['generation_requested', 'asset_received'].includes(record.workflow_status)) throw new Error("Generate a creative only after an asset decision."); const provider = args.provider || (record.asset ? "manual" : config().settings.workflow.image_provider); const dimensions = { width: 1080, height: 1350 };
 if (provider === "interactive_manifest") { record.creative_manifest = { format: "image", provider, status: "pending_interactive_generation", dimensions, prompt: fillTemplate("image-prompt-template.md", { business_name: config().business.name, topic: record.blog.title, audience: record.blog.audience, social_angle: record.brief.social_angle, visual_concept: record.brief.visual_concept, brand_style: config().brand.visual_style, dimensions: "1080 × 1350" }), output_destination: `public/generated-social/images/${record.topic_id}-background.png`, negative_instructions: config().brand.prohibited_visuals }; record.ai_calls.push({ purpose: "image_prompt", provider, at: now(), paid: false }); return saveRecord(record); }
 let source = record.asset?.working_path ? path.resolve(contentRoot, record.asset.working_path) : null;
 if (provider === "mock") { source = path.join(contentRoot, "drafts", record.topic_id, "mock-background.png"); fs.mkdirSync(path.dirname(source), { recursive: true }); await sharp({ create: { width: 1080, height: 1350, channels: 4, background: config().brand.colors.warm_ivory } }).composite([{ input: Buffer.from(`<svg width="1080" height="1350"><rect x="70" y="70" width="940" height="1210" rx="56" fill="#24352A"/><circle cx="860" cy="270" r="220" fill="#F47A32" opacity=".85"/><path d="M100 1000 L820 450 L990 1210 L100 1210Z" fill="#66743A" opacity=".72"/></svg>`) }]).png().toFile(source); }
 if (!source) throw new Error("No mock or supplied image is available for a final creative."); record.creative_manifest = { format: "image", provider, status: "ready", source_path: path.relative(contentRoot, source), dimensions, headline: record.brief.headline, supporting_text: record.brief.supporting_text, call_to_action: record.brief.call_to_action, website: config().business.website_url, instagram_handle: record.brief.instagram_handle, logo_path: config().brand.logo_path, brand: config().brand }; transition(record, "creative_generated", { provider }); return record;
}
export async function completeInteractiveGeneration(record, args) { if (record.workflow_status !== "generation_requested" || record.creative_manifest?.status !== "pending_interactive_generation") throw new Error("No interactive image-generation request is awaiting completion."); if (!args.path) throw new Error("--path is required for the generated image saved inside the repository."); record.asset = copyAsset(record, safeRelativeAsset(args.path), false, "not_applicable"); transition(record, "asset_received", { asset: record.asset.original_path, provider: "interactive_manifest" }); await inspectAsset(record); return generateCreative(record, { provider: "manual" }); }
function esc(value) { return String(value || "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char]); }
async function transparentLogoBuffer(file) { const { data, info } = await sharp(file).ensureAlpha().raw().toBuffer({ resolveWithObject: true }); for (let index = 0; index < data.length; index += info.channels) { const red = data[index]; const green = data[index + 1]; const blue = data[index + 2]; if (red > 210 && green > 210 && blue > 210) data[index + 3] = 0; } const inset = 24; return sharp(data, { raw: info }).extract({ left: inset, top: inset, width: info.width - (inset * 2), height: info.height - (inset * 2) }).png().toBuffer(); }
export async function createPreview(record) { if (!["creative_generated", "creative_review_required"].includes(record.workflow_status)) throw new Error("A preview requires a generated creative."); const manifest = record.creative_manifest; manifest.headline = record.brief.headline; manifest.supporting_text = record.brief.supporting_text; manifest.call_to_action = record.brief.call_to_action; const words = manifest.headline.split(/\s+/); const midpoint = Math.ceil(words.length / 2); const headlineLines = words.length > 3 ? [words.slice(0, midpoint).join(" "), words.slice(midpoint).join(" ")] : [manifest.headline]; const headlineMarkup = headlineLines.map((line, index) => `<tspan x="80" dy="${index === 0 ? 0 : 74}">${esc(line)}</tspan>`).join(""); const output = path.join(publicRoot, "images", `${record.topic_id}.png`); const logo = path.resolve(root, manifest.logo_path); const overlay = `<svg width="1080" height="1350" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="shade" x1="0" x2="1"><stop stop-color="#172019" stop-opacity=".82"/><stop offset=".62" stop-color="#172019" stop-opacity=".28"/><stop offset="1" stop-color="#172019" stop-opacity="0"/></linearGradient></defs><rect width="1080" height="1350" fill="url(#shade)"/><circle cx="0" cy="0" r="96" fill="#F47A32"/><circle cx="1080" cy="1350" r="132" fill="#F47A32"/><text x="80" y="760" font-family="Barlow Condensed, sans-serif" font-size="62" font-weight="700" fill="#FFFFFF">${headlineMarkup}</text><text x="80" y="930" font-family="Inter, sans-serif" font-size="39" fill="#FFFFFF">${esc(manifest.supporting_text)}</text><rect x="555" y="1170" width="465" height="78" rx="12" fill="#B85A2B"/><text x="579" y="1223" font-family="Inter, sans-serif" font-size="31" font-weight="700" fill="#FFFFFF">${esc(manifest.call_to_action)}</text><text x="80" y="1190" font-family="Inter, sans-serif" font-size="28" fill="#FFFFFF">${esc(manifest.instagram_handle)}</text><text x="80" y="1240" font-family="Inter, sans-serif" font-size="24" fill="#FFFFFF">${esc(manifest.website)}</text></svg>`;
 const composites = [{ input: Buffer.from(overlay), top: 0, left: 0 }]; if (fs.existsSync(logo)) composites.push({ input: await sharp(await transparentLogoBuffer(logo)).resize({ width: 230 }).png().toBuffer(), top: 65, left: 65, blend: "over" }); await sharp(path.resolve(contentRoot, manifest.source_path)).resize(1080, 1350, { fit: "cover" }).composite(composites).png().toFile(output); record.preview = { image_path: path.relative(root, output), image_public_url: `${config().settings.media_hosting.public_base_url}/generated-social/images/${record.topic_id}.png`, dimensions: { width: 1080, height: 1350 }, format: "png", created_at: now() }; transition(record, "creative_review_required", { preview: record.preview.image_path }); return record;
}
export function validation(record, { forPublish = false } = {}) { const problems = []; const settings = config().settings; const business = config().business; if (record.source_workflow_status !== "approved_for_publish") problems.push("Topic is not final-approved."); if (!record.asset_decision) problems.push("Asset question has not been answered."); if (!record.preview?.image_path || !fs.existsSync(path.join(root, record.preview.image_path))) problems.push("Static preview is missing."); if (record.preview?.dimensions?.width !== 1080 || ![1350, 1080].includes(record.preview?.dimensions?.height)) problems.push("Preview dimensions are not supported social-image dimensions."); if (!["png", "jpeg", "webp"].includes(record.preview?.format)) problems.push("Preview format is not supported."); if (!record.brief?.facebook_caption || !record.brief?.instagram_caption) problems.push("Platform captions are missing."); if (!fs.existsSync(path.join(root, config().brand.logo_path))) problems.push("Configured logo is missing."); if (business.phone_status === "verification_required") problems.push("Phone/WhatsApp remains unverified."); if (settings.media_hosting.status !== "confirmed") problems.push("Public media host remains provisional."); if (!/^https:\/\//.test(record.preview?.image_public_url || "")) problems.push("Media URL must use HTTPS."); if (!/^https:\/\//.test(record.blog.url || "")) problems.push("Blog URL must use HTTPS."); if (record.asset?.contains_children && record.asset.consent_status !== "confirmed") problems.push("Child-image consent is missing."); if (forPublish) { if (record.workflow_status !== "ready_to_publish") problems.push("Final creative approval is missing."); if (!config().social.posting_time && !process.argv.includes("--publish-now")) problems.push("Posting time is not configured; use explicit --publish-now only after activation."); ["META_APP_ID", "META_APP_SECRET", "META_USER_ACCESS_TOKEN", "META_PAGE_ACCESS_TOKEN", "INSTAGRAM_ACCOUNT_ID", "META_API_VERSION"].filter((key) => !process.env[key]).forEach((key) => problems.push(`${key} is not configured.`)); }
 return { ok: problems.length === 0, problems, checked_at: now() };
}
export function approve(record, args) { if (record.workflow_status !== "creative_review_required") throw new Error("Final approval requires a creative review."); const action = args.action; if (!['approve', 'request_changes', 'replace_asset', 'switch_to_image', 'switch_to_video', 'skip'].includes(action)) throw new Error("Invalid approval action."); record.approvals ||= []; record.approvals.push({ type: "final_creative", action, notes: args.notes || "", approved_by: args.by || "local_operator", at: now() }); if (action === "approve") { transition(record, "creative_approved", { approval: "final_creative" }); return transition(record, "ready_to_publish", { approval: "final_creative" }); } if (action === "skip") return transition(record, "skipped", { reason: args.notes || "Final creative skipped." }); if (action === "replace_asset") return transition(record, "awaiting_user_asset", { change_request: action }); if (action === "switch_to_video") return transition(record, "creative_approved", { change_request: action }); return transition(record, "generation_requested", { change_request: action }); }
function redact(value) { return value ? "[configured]" : "[missing]"; }
async function metaForm(endpoint, values) { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(values) }); if (!response.ok) throw new Error(`Meta request failed with HTTP ${response.status}.`); return response.json(); }
async function assertPublicUrl(url, label) { const response = await fetch(url, { method: "HEAD", redirect: "follow" }); if (!response.ok) throw new Error(`${label} is not publicly accessible.`); }
async function publishImageToMeta(platform, record) { const version = process.env.META_API_VERSION || "v22.0"; const token = process.env.META_PAGE_ACCESS_TOKEN; const base = `https://graph.facebook.com/${version}`; if (platform === "facebook") { const response = await metaForm(`${base}/${process.env.META_PAGE_ID || config().social.facebook_page_id}/photos`, { url: record.preview.image_public_url, caption: record.brief.facebook_caption, access_token: token }); return { post_id: response.post_id || response.id, post_url: null }; }
 const accountId = process.env.INSTAGRAM_ACCOUNT_ID; const media = await metaForm(`${base}/${accountId}/media`, { image_url: record.preview.image_public_url, caption: record.brief.instagram_caption, access_token: token }); const published = await metaForm(`${base}/${accountId}/media_publish`, { creation_id: media.id, access_token: token }); return { post_id: published.id, post_url: null };
}
export async function publish(record, args) { const platforms = args.platform ? [args.platform] : ["facebook", "instagram"]; if (platforms.some((platform) => !["facebook", "instagram"].includes(platform))) throw new Error("Unknown platform."); const dryRun = args["dry-run"] || process.env.SOCIAL_AUTO_PUBLISH !== "true" || config().settings.workflow.auto_publish !== true; const checks = validation(record, { forPublish: !dryRun }); const results = [];
 for (const platform of platforms) { const key = `${record.topic_id}:${record.creative_manifest?.format || "image"}:${platform}`; if (record.platform_results?.[platform]?.post_id) { results.push({ platform, idempotency_key: key, status: "skipped", reason: "Already published." }); continue; } const request = { platform, endpoint: platform === "facebook" ? `/${process.env.META_PAGE_ID || config().social.facebook_page_id}/photos` : "/{INSTAGRAM_ACCOUNT_ID}/media", media_url: record.preview?.image_public_url, caption: platform === "facebook" ? record.brief.facebook_caption : record.brief.instagram_caption, credentials: { page_access_token: redact(process.env.META_PAGE_ACCESS_TOKEN), user_access_token: redact(process.env.META_USER_ACCESS_TOKEN) } }; if (dryRun) { results.push({ platform, idempotency_key: key, status: "dry_run", request, validation: checks }); continue; } if (!checks.ok) throw new Error(`Publishing blocked: ${checks.problems.join(" ")}`); await assertPublicUrl(record.preview.image_public_url, "Media URL"); await assertPublicUrl(record.blog.url, "Blog URL"); const published = await publishImageToMeta(platform, record); results.push({ platform, idempotency_key: key, status: "published", ...published }); }
 record.last_publish_attempt = { at: now(), dry_run: Boolean(dryRun), results }; record.platform_results ||= {}; results.forEach((result) => { record.platform_results[result.platform] = result; }); saveRecord(record); appendLog({ event: "publish_attempt", topic_id: record.topic_id, dry_run: Boolean(dryRun), results }); return results;
}
export function nextAction(record) { return ({ topic_detected: "social:brief", topic_approved: "social:request-asset", awaiting_user_asset: "social:respond-asset", asset_received: "social:generate-prompts --provider manual", generation_requested: record.creative_manifest?.status === "pending_interactive_generation" ? "social:complete-generation --path <saved-image>" : "social:generate-prompts --provider mock", creative_generated: "social:preview", creative_review_required: "social:approve", ready_to_publish: "social:publish --dry-run" })[record.workflow_status] || "No further action required."; }
